# Generated by Django 4.2.3 on 2024-05-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jp_word", models.CharField(max_length=20)),
                ("en_word", models.CharField(max_length=30)),
                ("jp_sentence", models.CharField(max_length=100)),
                ("en_sentence", models.CharField(max_length=100)),
                ("card_img", models.ImageField(null=True, upload_to="images")),
                ("card_audio", models.FileField(null=True, upload_to="audio")),
                ("review_date", models.DateField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
